# fly.toml app configuration file generated for whiteboard-server on 2023-05-11T20:12:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whiteboard-server"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = true
