name: Application test & build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  BuildAndTestApplication:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Build and test client
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build-and-test:client
      - name: Build and test server
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build-and-test:server
